import React, { useEffect, useState } from 'react';
import { CalendarDays, Search } from 'lucide-react';
import { appointmentService, Appointment } from '../../services/appointment.service';
import { PageHeader } from '../../components/common/PageHeader';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { toast } from '../../utils/toast';

export const DoctorAppointments: React.FC = () => {
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setAppointments(await appointmentService.listDoctor({ date })); } catch { toast.error('Unable to load your appointments.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [date]);
  const action = async (id: string, operation: 'confirm' | 'start' | 'complete' | 'noShow') => { try { await ({ confirm: appointmentService.confirm, start: appointmentService.start, complete: appointmentService.complete, noShow: appointmentService.noShow }[operation])(id); toast.success('Appointment updated.'); load(); } catch { toast.error('This appointment cannot be updated right now.'); } };
  return <div className="space-y-6"><PageHeader title="My Appointment Calendar" subtitle="Your scheduled PHC consultations and visit status." /><div className="bg-white p-4 border border-slate-200 rounded-2xl flex gap-3"><CalendarDays className="w-5 h-5 text-[#1976D2]" /><input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="text-xs border rounded-lg px-3" /><div className="relative flex-1"><Search className="absolute w-4 h-4 left-3 top-2.5 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search a patient" className="w-full pl-9 py-2 text-xs border rounded-lg" /></div></div>{loading ? <LoadingSpinner /> : <div className="grid gap-3">{appointments.filter((item) => item.patient.fullName.toLowerCase().includes(search.toLowerCase())).map((item) => <article key={item.id} className="bg-white rounded-2xl border border-slate-200 p-5 flex flex-col md:flex-row md:items-center gap-4 justify-between"><div><p className="font-bold text-slate-900">{item.patient.fullName}</p><p className="text-xs text-slate-500 mt-1">{new Date(item.scheduledAt).toLocaleString()} · {item.durationMinutes} minutes</p><p className="text-xs text-slate-600 mt-2">{item.reason}</p></div><div className="flex items-center gap-2"><span className="px-2 py-1 bg-blue-50 text-[#1976D2] text-[10px] font-bold rounded">{item.status}</span>{item.status === 'SCHEDULED' && <button onClick={() => action(item.id, 'confirm')} className="px-3 py-2 text-xs bg-[#1976D2] text-white rounded-lg">Confirm</button>}{item.status === 'CONFIRMED' && <button onClick={() => action(item.id, 'start')} className="px-3 py-2 text-xs bg-[#1976D2] text-white rounded-lg">Start visit</button>}{item.status === 'IN_PROGRESS' && <button onClick={() => action(item.id, 'complete')} className="px-3 py-2 text-xs bg-emerald-600 text-white rounded-lg">Complete</button>}</div></article>)}</div>}</div>;
};
