import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { CalendarPlus, Search } from 'lucide-react';
import { appointmentService, Appointment } from '../../services/appointment.service';
import { adminService, PhcDoctor } from '../../services/admin.service';
import { PageHeader } from '../../components/common/PageHeader';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { toast } from '../../utils/toast';

export const AdminAppointments: React.FC = () => {
  const [searchParams] = useSearchParams();
  const [items, setItems] = useState<Appointment[]>([]); const [doctors, setDoctors] = useState<PhcDoctor[]>([]); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [booking, setBooking] = useState(Boolean(searchParams.get('patientId'))); const [form, setForm] = useState({ patientId: searchParams.get('patientId') || '', referralId: searchParams.get('referralId') || '', doctorId: '', scheduledAt: '', durationMinutes: 30, reason: '' });
  const load = async () => { setLoading(true); try { const [appointments, staff] = await Promise.all([appointmentService.listPhc({ date }), adminService.getDoctors()]); setItems(appointments); setDoctors(staff.filter((doctor) => doctor.status === 'ACTIVE')); } catch { toast.error('Unable to load appointments.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [date]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await appointmentService.create({ ...form, scheduledAt: new Date(form.scheduledAt).toISOString() }); toast.success('Appointment scheduled.'); setBooking(false); load(); } catch (error) { toast.error((error as { response?: { data?: { message?: string } } })?.response?.data?.message || 'Could not schedule the appointment.'); } };
  return <div className="space-y-6"><PageHeader title="Appointment Calendar" subtitle="Schedule PHC visits after a referral has been assigned to a doctor." action={<button onClick={() => setBooking(true)} className="px-4 py-2 bg-[#1976D2] text-white text-xs font-bold rounded-xl flex items-center gap-2"><CalendarPlus className="w-4 h-4" />Book appointment</button>} /><div className="bg-white p-4 border border-slate-200 rounded-2xl flex flex-col sm:flex-row gap-3"><input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="p-2 border rounded-lg text-xs" /><div className="relative flex-1"><Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search patient or doctor" className="w-full pl-9 p-2 border rounded-lg text-xs" /></div></div>{loading ? <LoadingSpinner /> : <AppointmentTable items={items.filter((item) => `${item.patient.fullName} ${item.doctor.fullName}`.toLowerCase().includes(search.toLowerCase()))} />}{booking && <div className="fixed inset-0 bg-slate-900/50 z-50 grid place-items-center p-4"><form onSubmit={submit} className="w-full max-w-lg bg-white rounded-2xl p-6 space-y-3"><h2 className="font-bold">Book PHC appointment</h2><p className="text-xs text-slate-500">The referral must already be assigned to the selected doctor.</p>{(['patientId', 'referralId'] as const).map((key) => <input key={key} required value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={key === 'patientId' ? 'Patient ID' : 'Assigned referral ID'} className="w-full p-2.5 border rounded-lg text-xs" />)}<select required value={form.doctorId} onChange={(event) => setForm({ ...form, doctorId: event.target.value })} className="w-full p-2.5 border rounded-lg text-xs"><option value="">Select available doctor</option>{doctors.map((doctor) => <option key={doctor.id} value={doctor.id}>{doctor.fullName} — {doctor.specialization || 'General'}</option>)}</select><input required type="datetime-local" value={form.scheduledAt} onChange={(event) => setForm({ ...form, scheduledAt: event.target.value })} className="w-full p-2.5 border rounded-lg text-xs" /><input required min="5" max="480" type="number" value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: Number(event.target.value) })} className="w-full p-2.5 border rounded-lg text-xs" /><textarea required minLength={3} value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} placeholder="Reason for visit" className="w-full p-2.5 border rounded-lg text-xs" /><div className="flex justify-end gap-2"><button type="button" onClick={() => setBooking(false)} className="px-3 py-2 text-xs">Cancel</button><button className="px-3 py-2 text-xs bg-[#1976D2] text-white rounded-lg">Schedule</button></div></form></div>}</div>;
};
const AppointmentTable = ({ items }: { items: Appointment[] }) => <div className="bg-white border border-slate-200 rounded-2xl overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4 text-left">TIME</th><th className="p-4 text-left">PATIENT</th><th className="p-4 text-left">DOCTOR</th><th className="p-4 text-left">REASON</th><th className="p-4 text-left">STATUS</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t"><td className="p-4">{new Date(item.scheduledAt).toLocaleString()}</td><td className="p-4 font-semibold">{item.patient.fullName}</td><td className="p-4">{item.doctor.fullName}</td><td className="p-4">{item.reason}</td><td className="p-4">{item.status}</td></tr>)}</tbody></table></div>;
