import React, { useEffect, useState } from 'react';
import { CalendarPlus, Eye, Search, X } from 'lucide-react';
import { phcPatientService, PhcPatient, PatientSummary } from '../../services/phc-patient.service';
import { PageHeader } from '../../components/common/PageHeader';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { toast } from '../../utils/toast';

export const AdminPatients: React.FC = () => { const [patients, setPatients] = useState<PhcPatient[]>([]); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<PatientSummary | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { phcPatientService.list({ limit: '100' }).then(setPatients).catch(() => toast.error('Unable to load patients.')).finally(() => setLoading(false)); }, []); const open = async (id: string) => { try { setSelected(await phcPatientService.summary(id)); } catch { toast.error('Unable to load patient details.'); } }; if (loading) return <LoadingSpinner />; return <div className="space-y-6"><PageHeader title="PHC Patient Directory" subtitle="Review patient details, assessments, referrals, and the ASHA worker who registered the patient." /><div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search patient" className="w-full bg-white border rounded-xl pl-9 p-2.5 text-xs" /></div><div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="text-left p-4">PATIENT</th><th className="text-left p-4">VILLAGE</th><th className="text-left p-4">REGISTERED BY ASHA</th><th className="p-4"></th></tr></thead><tbody>{patients.filter((p) => p.fullName.toLowerCase().includes(search.toLowerCase())).map((patient) => <tr key={patient.id} className="border-t"><td className="p-4 font-bold">{patient.fullName}<span className="block font-normal text-slate-400">{patient.age} years · {patient.gender}</span></td><td className="p-4">{patient.village.name}</td><td className="p-4">{patient.registeredBy.fullName}</td><td className="p-4"><button onClick={() => open(patient.id)} className="text-[#1976D2] flex gap-1"><Eye className="w-4 h-4" /> Details</button></td></tr>)}</tbody></table></div>{selected && <PatientModal summary={selected} onClose={() => setSelected(null)} />}</div>; };
const PatientModal = ({ summary, onClose }: { summary: PatientSummary; onClose: () => void }) => <div className="fixed inset-0 z-50 bg-slate-900/50 p-4 grid place-items-center"><div className="w-full max-w-2xl max-h-[90vh] overflow-auto bg-white rounded-2xl p-6"><div className="flex justify-between"><div><h2 className="font-bold text-lg">{summary.patient.fullName}</h2><p className="text-xs text-slate-500">{summary.patient.village.name} · {summary.patient.phone || 'No phone'}</p></div><button onClick={onClose}><X /></button></div><div className="grid sm:grid-cols-2 gap-4 mt-5 text-xs"><Info title="ASHA worker" value={summary.patient.registeredBy.fullName} /><Info title="Active referral" value={summary.activeReferrals[0] ? `${summary.activeReferrals[0].priority} · ${summary.activeReferrals[0].status}` : 'None'} /><Info title="Upcoming appointment" value={summary.upcomingAppointment ? new Date(summary.upcomingAppointment.scheduledAt).toLocaleString() : 'None'} /><Info title="Follow-ups" value={`${summary.pendingFollowUps.length} pending`} /></div><h3 className="font-bold text-sm mt-6">Latest risk predictions</h3><div className="mt-2 space-y-2">{summary.latestPredictions.map((p, i) => <div key={i} className="p-3 border rounded-xl flex justify-between text-xs"><span>{p.disease}</span><b className={p.riskLevel === 'HIGH' ? 'text-rose-600' : p.riskLevel === 'MEDIUM' ? 'text-amber-600' : 'text-emerald-600'}>{p.riskLevel} · {(p.probability * 100).toFixed(0)}%</b></div>)}</div>{summary.activeReferrals[0] && <a href={`/admin/appointments?patientId=${summary.patient.id}&referralId=${summary.activeReferrals[0].id}`} className="mt-6 inline-flex px-4 py-2 bg-[#1976D2] text-white rounded-lg text-xs font-bold gap-2"><CalendarPlus className="w-4 h-4" />Book appointment</a>}</div></div>;
const Info = ({ title, value }: { title: string; value: string }) => <div className="p-3 bg-slate-50 rounded-xl"><p className="text-slate-500">{title}</p><p className="font-bold text-slate-900 mt-1">{value}</p></div>;
