import { AudioModule, RecordingPresets, setAudioModeAsync, useAudioRecorder, useAudioRecorderState } from 'expo-audio';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { AssessmentModelInputs, modelInputFields } from '@/lib/ai-predictions';
import { ashaApi } from '@/lib/asha-api';
import { createUuid, offlineStorage } from '@/lib/offline-storage';

const quickSymptoms = ['Fever', 'Cough', 'Dizziness', 'Fatigue', 'Shortness of Breath', 'Nausea / Vomiting'];
const historyOptions = ['Diabetes', 'Hypertension', 'Heart Disease', 'Asthma', 'Kidney Disease', 'Allergies'];
type Assessment = Record<string, any>;
type Patient = { id: string | number; name?: string; age?: string | number; gender?: string };
const toList = (value: unknown) => Array.isArray(value) ? value.map(String).filter(Boolean) : typeof value === 'string' ? value.split(',').map((item) => item.trim()).filter(Boolean) : [];
const numberOrUndefined = (value: string) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : undefined; };

export default function HealthAssessmentScreen() {
  const router = useRouter();
  const { patientId, assessmentId } = useLocalSearchParams<{ patientId: string; assessmentId: string }>();
  const recorder = useAudioRecorder(RecordingPresets.HIGH_QUALITY);
  const recorderState = useAudioRecorderState(recorder);
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const speechLoading = false;
  const [name, setName] = useState(''); const [age, setAge] = useState(''); const [gender, setGender] = useState(''); const [height, setHeight] = useState(''); const [weight, setWeight] = useState('');
  const [temperature, setTemperature] = useState(''); const [systolicBP, setSystolicBP] = useState(''); const [diastolicBP, setDiastolicBP] = useState(''); const [heartRate, setHeartRate] = useState(''); const [oxygen, setOxygen] = useState('');
  const [symptoms, setSymptoms] = useState<string[]>([]); const [additionalSymptoms, setAdditionalSymptoms] = useState(''); const [history, setHistory] = useState<string[]>([]); const [medications, setMedications] = useState(''); const [notes, setNotes] = useState('');
  const [ocrText] = useState(''); const [transcript, setTranscript] = useState(''); const [modelInputs, setModelInputs] = useState<AssessmentModelInputs>({});
  const isEditing = Boolean(assessmentId);

  const load = useCallback(async () => {
    try {
      const [patientRaw, assessmentRaw] = await Promise.all([offlineStorage.getItem('patients'), offlineStorage.getItem('healthAssessments')]);
      const patients: Patient[] = patientRaw ? JSON.parse(patientRaw) : [];
      const stored: Assessment[] = assessmentRaw ? JSON.parse(assessmentRaw) : [];
      const existing = stored.find((item) => String(item.id) === String(assessmentId));
      const patient = patients.find((item) => String(item.id) === String(patientId ?? existing?.patientId));
      if (patient) { setName(patient.name || ''); setAge(patient.age === undefined ? '' : String(patient.age)); setGender(patient.gender || ''); }
      if (existing) {
        const vitals = existing.vitals || {};
        setName(existing.patientName || patient?.name || ''); setAge(existing.patientAge === undefined ? (patient?.age === undefined ? '' : String(patient.age)) : String(existing.patientAge)); setGender(existing.patientGender || patient?.gender || '');
        setHeight(String(existing.height ?? '')); setWeight(String(existing.weight ?? '')); setTemperature(String(vitals.temperature ?? existing.temperature ?? '')); setSystolicBP(String(vitals.systolicBP ?? existing.sysBP ?? '')); setDiastolicBP(String(vitals.diastolicBP ?? existing.diaBP ?? '')); setHeartRate(String(vitals.heartRate ?? existing.heartRate ?? '')); setOxygen(String(vitals.oxygenSaturation ?? existing.oxygenSaturation ?? ''));
        setSymptoms(toList(existing.symptoms).filter((item) => quickSymptoms.includes(item))); setAdditionalSymptoms(existing.additionalSymptoms || toList(existing.symptoms).filter((item) => !quickSymptoms.includes(item)).join(', ')); setHistory(toList(existing.medicalHistory)); setMedications(toList(existing.medications).join(', ')); setNotes(existing.additionalDetails || existing.notes || ''); setTranscript(existing.speechTranscript || ''); setModelInputs(existing.modelInputs || {});
      }
    } catch { Alert.alert('Error', 'Unable to load the assessment.'); } finally { setLoading(false); }
  }, [assessmentId, patientId]);
  useEffect(() => { void load(); }, [load]);
  const toggle = (value: string, setter: React.Dispatch<React.SetStateAction<string[]>>) => setter((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]);

  const choosePrescription = () => Alert.alert('OCR unavailable offline', 'This app has no bundled OCR ONNX model. OCR requires the AI service or a separate local OCR model.');
  const startRecording = async () => {
    try { const permission = await AudioModule.requestRecordingPermissionsAsync(); if (!permission.granted) { Alert.alert('Permission required', 'Microphone access is needed for voice input.'); return; } await setAudioModeAsync({ allowsRecording: true, playsInSilentMode: true }); await recorder.prepareToRecordAsync(); recorder.record(); }
    catch { Alert.alert('Recording unavailable', 'Unable to start voice recording.'); }
  };
  const stopRecording = async () => {
    try { await recorder.stop(); Alert.alert('Speech-to-text unavailable offline', 'This app has no bundled speech-recognition ONNX model.'); }
    catch { Alert.alert('Recording unavailable', 'Unable to stop voice recording.'); }
  };
  const saveAssessment = async () => {
    const numericVitals = { Temperature: numberOrUndefined(temperature), Systolic_BP: numberOrUndefined(systolicBP), Diastolic_BP: numberOrUndefined(diastolicBP), Heart_Rate: numberOrUndefined(heartRate), Oxygen: numberOrUndefined(oxygen) };
    const payload = { patient_name: name.trim(), age: numberOrUndefined(age), gender, height: numberOrUndefined(height), weight: numberOrUndefined(weight), ...Object.fromEntries(Object.entries(numericVitals).filter(([, value]) => value !== undefined)), symptoms: [...symptoms, ...toList(additionalSymptoms)], medical_history: history, current_medications: toList(medications), additional_notes: notes.trim(), ocr_text: ocrText, speech_transcript: transcript };
    try {
      setSubmitting(true);
      const raw = await offlineStorage.getItem('healthAssessments'); const all: Assessment[] = raw ? JSON.parse(raw) : []; const id = assessmentId || createUuid(); const record = { id, patientId: patientId || 'unknown', patientName: name.trim(), patientAge: numberOrUndefined(age), patientGender: gender, date: new Date().toISOString(), riskLevel: 'Pending', risk_level: 'Pending', height: numberOrUndefined(height), weight: numberOrUndefined(weight), symptoms: payload.symptoms, additionalSymptoms, medicalHistory: history, medications: toList(medications), additionalDetails: notes.trim(), ocrText, speechTranscript: transcript, modelInputs, vitals: { temperature: numericVitals.Temperature, systolicBP: numericVitals.Systolic_BP, diastolicBP: numericVitals.Diastolic_BP, heartRate: numericVitals.Heart_Rate, oxygenSaturation: numericVitals.Oxygen } };
      const updated = isEditing ? all.map((item) => String(item.id) === String(id) ? { ...item, ...record } : item) : [record, ...all]; await offlineStorage.setItem('healthAssessments', JSON.stringify(updated));
      if (!isEditing && patientId) void ashaApi.createAssessment({ id: String(id), patientId, oxygenSaturation: numericVitals.Oxygen, heartRate: numericVitals.Heart_Rate, systolicBp: numericVitals.Systolic_BP, diastolicBp: numericVitals.Diastolic_BP, symptoms: payload.symptoms, notes: notes.trim() || undefined, inputSource: 'MANUAL', clientCreatedAt: record.date }).catch(() => undefined);
      Alert.alert('Saved', 'Assessment saved locally. Run the bundled ONNX disease models from the Predictions screen.');
    } catch { Alert.alert('Save failed', 'Unable to save the assessment.'); } finally { setSubmitting(false); }
  };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#0D9488" /><Text style={styles.loadingText}>Loading assessment…</Text></View>;
  const Input = ({ label, value, setValue, numeric = false, multiline = false }: { label: string; value: string; setValue: (text: string) => void; numeric?: boolean; multiline?: boolean }) => <View style={styles.inputGroup}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} value={value} onChangeText={setValue} keyboardType={numeric ? 'decimal-pad' : 'default'} multiline={multiline} textAlignVertical={multiline ? 'top' : 'center'} placeholderTextColor="#94A3B8" /></View>;
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>‹</Text></TouchableOpacity><Text style={styles.title}>{isEditing ? 'Edit Assessment' : 'Patient Assessment'}</Text></View>
    <View style={styles.card}><Text style={styles.section}>Patient Information</Text><Input label="Patient Full Name" value={name} setValue={setName} /><Input label="Age" value={age} setValue={setAge} numeric /><Text style={styles.label}>Gender</Text><View style={styles.chips}>{['Female', 'Male', 'Other'].map((item) => <TouchableOpacity key={item} style={[styles.chip, gender === item && styles.selectedChip]} onPress={() => setGender(item)}><Text style={[styles.chipText, gender === item && styles.selectedChipText]}>{item}</Text></TouchableOpacity>)}</View><Input label="Height (cm)" value={height} setValue={setHeight} numeric /><Input label="Weight (kg)" value={weight} setValue={setWeight} numeric /></View>
    <View style={styles.card}><Text style={styles.section}>Vital Signs</Text><Input label="Temperature (°F)" value={temperature} setValue={setTemperature} numeric /><View style={styles.row}><View style={styles.flex}><Input label="Systolic BP" value={systolicBP} setValue={setSystolicBP} numeric /></View><View style={styles.flex}><Input label="Diastolic BP" value={diastolicBP} setValue={setDiastolicBP} numeric /></View></View><Input label="Heart Rate (bpm)" value={heartRate} setValue={setHeartRate} numeric /><Input label="SpO2 (%)" value={oxygen} setValue={setOxygen} numeric /></View>
    <View style={styles.card}><Text style={styles.section}>Symptoms</Text><Text style={styles.label}>Quick Symptoms</Text><View style={styles.chips}>{quickSymptoms.map((item) => <TouchableOpacity key={item} style={[styles.chip, symptoms.includes(item) && styles.selectedChip]} onPress={() => toggle(item, setSymptoms)}><Text style={[styles.chipText, symptoms.includes(item) && styles.selectedChipText]}>{item}</Text></TouchableOpacity>)}</View><Input label="Additional Symptoms" value={additionalSymptoms} setValue={setAdditionalSymptoms} multiline /></View>
    <View style={styles.card}><Text style={styles.section}>Medical History</Text><View style={styles.chips}>{historyOptions.map((item) => <TouchableOpacity key={item} style={[styles.chip, history.includes(item) && styles.selectedChip]} onPress={() => toggle(item, setHistory)}><Text style={[styles.chipText, history.includes(item) && styles.selectedChipText]}>{item}</Text></TouchableOpacity>)}</View><Input label="Current Medications" value={medications} setValue={setMedications} /><Input label="Additional Notes" value={notes} setValue={setNotes} multiline /></View>
    <View style={styles.card}><Text style={styles.section}>Prescription Image OCR</Text><TouchableOpacity style={styles.secondaryButton} onPress={choosePrescription}><Text style={styles.secondaryText}>Unavailable offline</Text></TouchableOpacity></View>
    <View style={styles.card}><Text style={styles.section}>Voice Input</Text><View style={styles.row}><TouchableOpacity style={[styles.secondaryButton, styles.flex]} onPress={() => void startRecording()} disabled={recorderState.isRecording || speechLoading}><Text style={styles.secondaryText}>{recorderState.isRecording ? 'Recording…' : 'Start Recording'}</Text></TouchableOpacity><TouchableOpacity style={[styles.stopButton, styles.flex]} onPress={() => void stopRecording()} disabled={!recorderState.isRecording || speechLoading}>{speechLoading ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.stopText}>Stop Recording</Text>}</TouchableOpacity></View><Input label="Speech transcript" value={transcript} setValue={setTranscript} multiline /></View>
    <View style={styles.card}><Text style={styles.section}>Disease Model Inputs</Text><Text style={styles.helper}>These values run locally against the bundled ONNX disease models.</Text>{modelInputFields.map(([key, label]) => <Input key={key} label={label} value={modelInputs[key] === undefined ? '' : String(modelInputs[key])} setValue={(value) => setModelInputs((current) => ({ ...current, [key]: value }))} numeric />)}</View>
    <TouchableOpacity style={[styles.primaryButton, submitting && styles.disabled]} disabled={submitting} onPress={() => void saveAssessment()}>{submitting ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.primaryText}>Save Assessment</Text>}</TouchableOpacity>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#F8FAFC' }, content: { padding: 16, paddingBottom: 36 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, loadingText: { marginTop: 10, color: '#64748B' }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 }, back: { color: '#0F172A', fontSize: 34, lineHeight: 34 }, title: { color: '#0F172A', fontSize: 22, fontWeight: '800' }, card: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: '#E2E8F0' }, section: { color: '#0F172A', fontSize: 16, fontWeight: '800', marginBottom: 12 }, label: { color: '#334155', fontSize: 13, fontWeight: '700', marginBottom: 6 }, inputGroup: { marginBottom: 12 }, input: { borderColor: '#CBD5E1', borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, color: '#0F172A', backgroundColor: '#F8FAFC' }, multiline: { minHeight: 80 }, row: { flexDirection: 'row', gap: 10 }, flex: { flex: 1 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 }, chip: { borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7 }, selectedChip: { borderColor: '#0D9488', backgroundColor: '#CCFBF1' }, chipText: { color: '#475569', fontSize: 12, fontWeight: '600' }, selectedChipText: { color: '#0F766E' }, secondaryButton: { alignItems: 'center', justifyContent: 'center', minHeight: 45, borderRadius: 10, borderWidth: 1, borderColor: '#0D9488', backgroundColor: '#F0FDFA', padding: 10 }, secondaryText: { color: '#0F766E', fontWeight: '700' }, stopButton: { alignItems: 'center', justifyContent: 'center', minHeight: 45, borderRadius: 10, backgroundColor: '#DC2626', padding: 10 }, stopText: { color: '#FFFFFF', fontWeight: '700' }, result: { backgroundColor: '#F0FDFA', borderRadius: 10, padding: 12, marginTop: 12 }, resultLabel: { color: '#0F766E', fontWeight: '800', fontSize: 12, marginBottom: 5 }, resultText: { color: '#334155', lineHeight: 19 }, triageTitle: { color: '#0F766E', fontSize: 17, fontWeight: '800', marginBottom: 10 }, backendNote: { color: '#64748B', fontSize: 12, marginTop: 10, fontStyle: 'italic' }, helper: { color: '#64748B', fontSize: 12, lineHeight: 17, marginBottom: 12 }, primaryButton: { alignItems: 'center', justifyContent: 'center', minHeight: 52, borderRadius: 12, backgroundColor: '#0D9488', marginTop: 4 }, primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' }, disabled: { opacity: 0.65 } });
